### ISSUE TITLE
Support for use on non-tags

### ISSUE THREAD

**Issue by leighmcculloch** [taiki-e/upload-rust-binary-action#34]
Something I've noticed is that the current action can only be executed from a tag, due to these lines:

https://github.com/taiki-e/upload-rust-binary-action/blob/0b10335ed20430900b5597e792b8f95be95e8aa2/main.sh#L24-L27

There are cases that a binary release might be run from a branch rather than from a tag. An example of this is when retroactively running a CI job for an already released tag.

**Comment by taiki-e** [comment]
Since GitHub releases are associated with tags, to know which release to upload binaries to, we need information about the tag.

It refers to GITHUB_REF by default, but you can specify this using the [`ref` input option](https://github.com/taiki-e/upload-rust-binary-action/blob/0b10335ed20430900b5597e792b8f95be95e8aa2/action.yml#L58-L63).
Therefore, you can create a release from any event by specifying the `ref` input option.

**Comment by taiki-e** [comment]
Documented as https://github.com/taiki-e/upload-rust-binary-action#supported-events.

**Comment by leighmcculloch** [comment]
Thanks, that's very helpful. Thank you!
